# Generated by Django 2.2.12 on 2021-06-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.IntegerField(default=2000),
        ),
    ]
